version: "3"

services:

  # db:

  backend:
    build:
      context: ./backEndProject
      args:
        DJANGO_ALLOWED_HOSTS: "*"
        DJANGO_SECRET_KEY: "*"
        DJANGO_CORS_ORIGIN_WHITELIST: "*"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backEndProject/:/backEndProject/
    expose:
      - 8000
    env_file:
      - ./backEndProject/settings/dev/.env.dev # path setting needed

  # frontend: